# Select base image
FROM selenium/standalone-firefox

# Identify the maintainer of an image
LABEL maintainer="ronaldo.aguirre@protonmail.com"

# RUN cd /home && sudo mkdir scrap
WORKDIR /home/scrap

# Expose port 4444
EXPOSE 4444